"""Add Meraki Organization

Revision ID: c32733f4fd1c
Revises: 
Create Date: 2025-06-11 14:55:07.963216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c32733f4fd1c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meraki_organizations',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('remote_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('api_enabled', sa.Boolean(), nullable=True),
    sa.Column('licensing_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cloud_region_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cloud_region_host_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('management_msp_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meraki_organizations')
    # ### end Alembic commands ###
